version: "3.7"

volumes:
  elasticsearch-data: {}

networks:
  private: {}
  public: {}

services:
  kibana:
    image: kibana:7.4.2
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        tag: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - private
      - public
    labels:
      - logging.efk.service=kibana

  fluent-bit:
    image: fluent/fluent-bit:1.3.2
    depends_on:
      - elasticsearch
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    ports:
      # This port should be closed for the outside world
      - 24224:24224
    networks:
      - private
    labels:
      - logging.efk.service=fluent-bit

  elasticsearch:
    image: elasticsearch:7.4.2
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        tag: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - private
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      "discovery.type": "single-node"
